### ISSUE TITLE
How to use this plugin with Nuxt.js

### ISSUE THREAD

**Issue by strunkie30** [jantimon/iconfont-webpack-plugin#20]
How to use this plugin with Nuxt.js? The following configuration does not work.

Nuxt configuration
```javascript
build: {
    postcss: (loader) => [
        require('iconfont-webpack-plugin')({ resolve: loader.resolve })
    ]
}
```

SCSS code
```scss
p {
    &:before {
        content: "";
        font-icon: url('~/assets/icons/arrow-left.svg');
        transition: 0.5s color;
    }
}
```

Compiled CSS
```css
p:before {
    content: "";
    font-icon: url(data:image/svg+xml;base64,PHN2ZyBmaWxsPSIjMDAwMDAwIiBoZWlnaHQ9IjI0IiB2aWV3Q…Z6Ii8+CiAgICA8cGF0aCBkPSJNMC0uNWgyNHYyNEgweiIgZmlsbD0ibm9uZSIvPgo8L3N2Zz4=);
    -webkit-transition: 0.5s color;
    transition: 0.5s color;
}
```
