### ISSUE TITLE
Fill color doesn't work for background SVG images

### ISSUE THREAD

**Issue by equinusocio** [jantimon/iconfont-webpack-plugin#26]
Hi, just to tell you that this point in the readme is not totally true. You should specify that there are many techniques to define and use icons. You can use svg in different ways and modify his color, even on IE9+. Icon fonts are now considered hacks since there are many approaches with a more specific technology.

### 1. Mask
https://codepen.io/noahblon/post/coloring-svgs-in-css-background-images

```css
.icon {
    background-color: red;
    mask: url(icon.svg) no-repeat 50% 50%;
}
```

---

### 2. As plain svg background
https://css-tricks.com/probably-dont-base64-svg/

```css
  background-image: url('data:image/svg+xml;utf8,<svg ...><g stroke="var(--color)" ... /></g></svg>');
```

---

### 3. Using filters on a 50% gray icon.
http://noahblon.com/coloring-svgs-in-css-background-images/

```css
.icon {
    filter: hue-rotate(220deg) saturate(5);
}
```

---

### 4. Using currentColor
https://css-tricks.com/cascading-svg-fill-color/

```css
svg {
  fill: currentColor;
}

.icon {
  color: red;
}
```

---

### 5. External svg sprite and background

```html
<svg xmlns="http://www.w3.org/2000/svg">

    <symbol id="arrow-left" viewBox="0 0 10 16">
        <path d="M9.4 1.4L8 0 0 8l8 8 1.4-1.4L2.8 8z"/>
    </symbol>

    <symbol id="arrow-right" viewBox="0 0 10 16">
        <path d="M0 14.6L1.4 16l8-8-8-8L0 1.4 6.6 8z"/>
    </symbol>

</svg>
```

```css
.icon{
  background: url("https://path-to-svg-sprite.svg#arrow-right") no-repeat;
}
```

You can combine this with other methods.

**Comment by jantimon** [comment]
Which of the methods would work in IE9+?

**Comment by equinusocio** [comment]
@jantimon `currentColor` is supported on IE9+

**Comment by equinusocio** [comment]
@jantimon No but the point of my issue is not "using only background". The point of the readme talk about the impossibility to change the icon fill if you use svg as background image (not related to IE9)..the key here is that svg can be used in multiple ways and not only as background. This not means that svg fonts are a good replacement (it is useful only for the IE 9+ support) but for modern browser there are alot better ways.

If someone want to use icons there are many modern approaches to use them and then just go for a graceful-degradation. If you really need to support such older browsers instead to overload the css weight with inlined fonts users can just provide a [fallback with one line of css](https://css-tricks.com/svg-fallbacks/). 

The last two points
- Fill color doesn't work for background SVG images
- Inline SVGs are resolved relative to the page not to the css

Are not directly related to "why use fonts over svgs."..

**Comment by jantimon** [comment]
Okay than I got you wrong - I though you had a better approaches if you want to target all common browsers.

Why do you think `Fill color doesn't work for background SVG images` is not true as long as IE11 has to be supported in many web projects?

I used this approach for a pattern library which was used on multiple domains.  
The consumers just added the css file and all icons worked because all paths are relative to the css.  
Why do you think that's wrong?

**Comment by equinusocio** [comment]
They are both correct! But these key points not related (in my opinion) to choosing fonts over svgs (When should you use icon fonts over pure SVGs?). 

The first one is a minus only if you use svg's as background, but it's not an svg limitation, it is just a way to use svg's (not even with normal images you can manipulate them). It's same as telling that if you use fonts you can't manipulate icons paths with css animations (a thing that you can do with plain svg) :). These are just choises that doesn't not reflect minus or plus.

I just think you should not tell when to choose which one, but let user know about all limitation (both svg and fonts) and not telling only the fonts advantages. Right now the readme does not tell the full truth :)

This is just my opinion. Sorry, english is not my language but i'm here in peace :D feel free to close this issue.

**Comment by jantimon** [comment]
@equinusocio I really like your first solution as it is a full replacement for all requirements the iconfont-webpack-plugin is trying to address.

We could add a new option which might be `legacyBrowserSupport` which is set to `true` by default and switch to your `svg-mask` approach if set to `false`.

We would have to measure the size of the svg to have the correct height/width ratio and translate it to em to achieve the exact same effect.

That way people could use svgs for modern browsers and fallback to icon-fonts if needed.  
Would you be interested in working on that?

**Comment by equinusocio** [comment]
I’m not a javascript developer 😅 i don’t know if i can really help you. I’m focused on html / css architectures. 

Btw, using the mask approach the svg size should not be computed. These sizes are relative to the element box or can be pixels. So the user should be able to declare these sizes

**Comment by jantimon** [comment]
To bad :(
If we would use EM the size could easily be set using a font-size.

Overall this would work very similar to the legacy solution

**Comment by equinusocio** [comment]
Intead to use the shorthand expression the user can just set `background-size` and use font size for text

**Comment by jantimon** [comment]
Hm it sounds like you don't understand what I mean - should I explain what the iconfont-webpack-plugin actually does?

**Comment by equinusocio** [comment]
What i don't understand is:

```
a:before {
  font-icon: 80% url('./account.svg');
}
```

80% of what?

Maybe this can be translated to:

```css
.icon {
    background-color: red;
    mask: url('./account.svg);
    mask-repeat: no-repeat;
    mask-size: 80%;
}
```

**Comment by jantimon** [comment]
https://github.com/jantimon/iconfont-webpack-plugin/blob/2e98e91f1e002e19b50d571a8704bfa696b6a87c/lib/postcss-plugin.js#L108-L123

`80%` is converted into `font-size: 80%`

For your mask approach

```css
a:before {
  font-icon: 80% url('./account.svg');
}
```

should probably translate to

```css
a:before {
  display: inline-block;
  width: 1em;
  background-color: currentColor;
  mask: url('./account.svg') no-repeat 100% 100%;
  font-size: 80%;
}
```

However the width (`1em`) depends on the width height ratio of `account.svg`.
Otherwise it would be stretched - wouldn't it?
